"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import TopNav from "@/components/top-nav";
import { Example } from "../components/Example";
import Navbar from "@/components/navbar";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        < TopNav />
        <Navbar />
        <Example />
        {children}</body>
    </html>
  );
}
